# Generated by Django 5.2.5 on 2025-09-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='league',
            field=models.CharField(choices=[('premier_league', 'Premier League'), ('serie_a', 'Serie A'), ('bundesliga', 'Bundesliga'), ('ligue_1', 'Ligue 1'), ('la_liga', 'La Liga'), ('mls', 'MLS'), ('super_lig', 'Süper Lig'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
