# Generated by Django 5.2.5 on 2025-09-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news_league'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveScore',
        ),
    ]
