# Generated by Django 5.2.7 on 2025-10-25 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('league', models.CharField(choices=[('premier_league', 'Premier League'), ('serie_a', 'Serie A'), ('bundesliga', 'Bundesliga'), ('ligue_1', 'Ligue 1'), ('la_liga', 'La Liga'), ('mls', 'MLS'), ('super_lig', 'Süper Lig'), ('efl', 'EFL'), ('champions_league', 'Champions League'), ('europa_league', 'Europa League')], max_length=20)),
                ('introduction', models.TextField()),
                ('home_team_form', models.TextField()),
                ('away_team_form', models.TextField()),
                ('injury_news', models.TextField()),
                ('tactical_preview', models.TextField()),
                ('predicted_lineups', models.TextField()),
                ('prediction', models.CharField(max_length=100)),
                ('author', models.CharField(default='Football Daily Team', max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='match_previews/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('upcoming', 'Upcoming')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Match Preview',
                'verbose_name_plural': 'Match Previews',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='TransferReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('from_team', models.CharField(max_length=100)),
                ('to_team', models.CharField(max_length=100)),
                ('transfer_fee', models.CharField(blank=True, max_length=50)),
                ('league', models.CharField(choices=[('premier_league', 'Premier League'), ('serie_a', 'Serie A'), ('bundesliga', 'Bundesliga'), ('ligue_1', 'Ligue 1'), ('la_liga', 'La Liga'), ('mls', 'MLS'), ('super_lig', 'Süper Lig'), ('efl', 'EFL'), ('champions_league', 'Champions League'), ('europa_league', 'Europa League')], max_length=20)),
                ('introduction', models.TextField()),
                ('player_background', models.TextField()),
                ('team_fit', models.TextField()),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('value_for_money', models.TextField()),
                ('final_verdict', models.TextField()),
                ('author', models.CharField(default='Football Daily Team', max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='transfer_reviews/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('rumor', 'Rumor')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Transfer Review',
                'verbose_name_plural': 'Transfer Reviews',
                'ordering': ['-published_at'],
            },
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.AlterField(
            model_name='news',
            name='league',
            field=models.CharField(choices=[('premier_league', 'Premier League'), ('serie_a', 'Serie A'), ('bundesliga', 'Bundesliga'), ('ligue_1', 'Ligue 1'), ('la_liga', 'La Liga'), ('mls', 'MLS'), ('super_lig', 'Süper Lig'), ('efl', 'EFL'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
